"""
Interview API
==============

FastAPI application with REST + WebSocket endpoints for the AI Interviewer.

REST Endpoints (called by .NET backend)
----------------------------------------
POST   /api/interview/prepare           — Create session with plan data
GET    /api/interview/{session_id}/status — Check session status
GET    /api/interview/{session_id}/transcript — Get final interview transcript
DELETE /api/interview/{session_id}       — Delete a session
GET    /health                           — Server health check

WebSocket Endpoint (opened by React frontend)
----------------------------------------------
WS     /ws/interview/{session_id}        — Real-time interview session

WebSocket Protocol
------------------
Server -> Client (text frames = JSON):
    { type: "intro",    text: "...", state: "INTRO" }
    { type: "question", text: "...", state: "ASK",      question_index: 1, total_questions: 5 }
    { type: "followup", text: "...", state: "FOLLOWUP", question_index: 1, total_questions: 5 }
    { type: "close",    text: "...", state: "CLOSE" }
    { type: "complete", report: {...} }
    { type: "tts_start" }
    { type: "tts_end" }
    { type: "error",    message: "..." }

Server -> Client (binary frames):
    Raw TTS audio chunks (PCM/WAV, stream between tts_start and tts_end)

Client -> Server (text frames = JSON):
    { type: "answer", text: "..." }          — Pre-transcribed answer
    { type: "answer_audio" }                 — Signals next binary frame is audio

Client -> Server (binary frames):
    Raw audio data for STT (sent after "answer_audio" signal)
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
import time
import uuid
from contextlib import asynccontextmanager

import httpx
from typing import Any, Optional

from fastapi import FastAPI, WebSocket, WebSocketDisconnect, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# -- Ensure project root is importable ------------------------------------
sys.path.insert(0, os.path.dirname(__file__))

from config import get_key, get_key_int

from session import session_manager, SessionNotFoundError, SessionStateError
from storage import HybridReportStorage

report_storage = HybridReportStorage(session_manager)
from stt import transcribe, build_technical_prompt
from tts import synthesize_streaming
from evaluator.router import router as evaluator_router
from evaluator.pipeline import run_evaluation

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(name)s | %(levelname)s | %(message)s",
)


# ========================================================================
# Pydantic models (request/response schemas)
# ========================================================================

class QuestionInput(BaseModel):
    """A single interview question from the Planner."""
    question: str
    golden_answer: str
    skill: str
    rationale: Optional[str] = None
    time_limit_seconds: Optional[int] = None


class PrepareRequest(BaseModel):
    """
    Request body for POST /api/interview/prepare.

    Sent by the .NET backend after running the Planner.
    """
    session_id: str = Field(
        ...,
        description="Unique session ID (GUID generated by .NET backend)",
    )
    candidate_name: str = Field(..., description="Candidate's full name")
    job_role: str = Field(..., description="Target job role")
    level: str = Field(
        "Junior",
        description="Experience level: Junior, Mid, or Senior",
    )
    duration_limit: int = Field(
        1800,
        description="Duration limit of the interview in seconds",
    )
    questions: list[QuestionInput] = Field(
        ...,
        min_length=1,
        description="Interview questions from the Planner",
    )


class PrepareResponse(BaseModel):
    session_id: str
    status: str
    candidate_name: str
    total_questions: int
    websocket_url: str


class SessionStatusResponse(BaseModel):
    session_id: str
    status: str
    candidate_name: str
    job_role: str
    total_questions: int
    created_at: Optional[str] = None
    activated_at: Optional[str] = None
    completed_at: Optional[str] = None
    age_hours: float = 0.0


class ReportResponse(BaseModel):
    session_id: str
    status: str
    report: Optional[dict[str, Any]] = None


# ========================================================================
# InterviewPlan adapter (converts PrepareRequest to plan-like object)
# ========================================================================

class PlanFromRequest:
    """
    Adapts PrepareRequest into the plan object that InterviewOrchestrator expects.

    The orchestrator accesses: plan.session_id, plan.candidate_name,
    plan.job_role, plan.level, plan.questions[].question/golden_answer/skill
    """

    def __init__(self, req: PrepareRequest):
        self.session_id = req.session_id
        self.candidate_name = req.candidate_name
        self.job_role = req.job_role
        self.level = req.level
        self.duration_limit = req.duration_limit
        self.questions = [
            _QuestionAdapter(q) for q in req.questions
        ]


class _QuestionAdapter:
    """Adapts QuestionInput to the attribute-access interface the orchestrator uses."""

    def __init__(self, q: QuestionInput):
        self.question = q.question
        self.golden_answer = q.golden_answer
        self.skill = q.skill


# ========================================================================
# App lifecycle
# ========================================================================

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup/shutdown hooks."""
    logger.info("Interview API starting up...")
    yield
    # Cleanup stale sessions on shutdown
    cleaned = session_manager.cleanup_stale_sessions(max_age_hours=0)
    logger.info(f"Shutdown cleanup: removed {cleaned} sessions")


# ========================================================================
# FastAPI app
# ========================================================================

app = FastAPI(
    title="AI Interviewer API",
    description="REST + WebSocket API for the AI Interview System",
    version="1.0.0",
    lifespan=lifespan,
)

# -- CORS (allow React frontend) ------------------------------------------
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Tighten in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# -- Evaluator router ---------------------------------------------------------
app.include_router(evaluator_router)


# ========================================================================
# REST Endpoints
# ========================================================================

from fastapi.responses import RedirectResponse

@app.get("/")
async def root():
    """Redirect to the API documentation."""
    return RedirectResponse(url="/docs")

@app.get("/health")
async def health_check():
    """Server health check."""
    return {
        "status": "ok",
        "active_sessions": session_manager.active_count,
        "total_sessions": session_manager.total_count,
    }


@app.post("/api/interview/prepare", response_model=PrepareResponse)
async def prepare_interview(req: PrepareRequest):
    """
    Create an interview session from the Planner's output.

    Called by the .NET backend after it runs the Planner.
    The session_id is generated by .NET and passed here.
    """
    # Check for duplicate session
    try:
        existing = session_manager.get_session_status(req.session_id)
        raise HTTPException(
            status_code=409,
            detail=f"Session {req.session_id} already exists (status: {existing})",
        )
    except SessionNotFoundError:
        pass  # Good — session doesn't exist yet

    # Convert request to plan object
    plan = PlanFromRequest(req)

    # Create the session
    session_id = session_manager.create_session(plan)

    logger.info(
        f"Session prepared | id={session_id} "
        f"candidate={req.candidate_name} "
        f"questions={len(req.questions)}"
    )

    return PrepareResponse(
        session_id=session_id,
        status="pending",
        candidate_name=req.candidate_name,
        total_questions=len(req.questions),
        websocket_url=f"/ws/interview/{session_id}",
    )


@app.get("/api/interview/{session_id}/status", response_model=SessionStatusResponse)
async def get_session_status(session_id: str):
    """Get the current status of an interview session."""
    try:
        info = session_manager.get_session_info(session_id)
        return SessionStatusResponse(**info)
    except SessionNotFoundError:
        raise HTTPException(status_code=404, detail=f"Session not found: {session_id}")


@app.get("/api/interview/{session_id}/transcript", response_model=ReportResponse)
async def get_session_transcript(session_id: str):
    """
    Get the final interview transcript (report).

    Only available after the interview is completed.
    """
    # 1. Try to fetch from hybrid storage (Redis -> RAM)
    report = report_storage.get_report(session_id)
    if report:
        return ReportResponse(
            session_id=session_id,
            status="completed",
            report=report,
        )

    # 2. If not found in storage, check session_manager directly to see if the session exists but isn't completed
    try:
        status = session_manager.get_session_status(session_id)
        if status != "completed":
            raise HTTPException(
                status_code=400,
                detail=f"Interview not completed yet (status: {status})",
            )
        # If it says completed but report wasn't returned, something is wrong
        raise HTTPException(status_code=404, detail="Report data not found.")
    except SessionNotFoundError:
        raise HTTPException(status_code=404, detail=f"Session not found: {session_id}")


@app.delete("/api/interview/{session_id}")
async def delete_session(session_id: str):
    """
    Delete a session and its report.
    """
    # The storage layer deletes from both Redis and RAM
    report_storage.delete_report(session_id)
    return {"status": "deleted", "session_id": session_id}


# ========================================================================
# Evaluation helper
# ========================================================================

async def _save_and_evaluate(session_id: str, report: dict) -> None:
    """
    Save the interview report and auto-trigger the evaluation pipeline
    in the background so the WebSocket response is not delayed.

    After evaluation completes, the result is pushed to the .NET webhook
    configured via the WEBHOOK_URL key in api_keys.json or environment.
    """
    report_storage.save_report(session_id, report)

    async def _run():
        try:
            logger.info(f"[Evaluator] Auto-triggering evaluation for session {session_id}")
            result = await asyncio.to_thread(run_evaluation, session_id)

            # Merge evaluation result into the stored report
            merged = {**report, "evaluation": result}
            report_storage.save_report(session_id, merged)
            logger.info(
                f"[Evaluator] Evaluation complete for session {session_id} "
                f"— avg_score={result.get('average_score')}"
            )

            # ── Webhook push ─────────────────────────────────────────────
            webhook_url = get_key("WEBHOOK_URL")
            if webhook_url:
                try:
                    async with httpx.AsyncClient(timeout=15.0) as client:
                        response = await client.post(webhook_url, json=result)
                        response.raise_for_status()
                    logger.info(
                        f"[Webhook] Successfully pushed evaluation for session {session_id} "
                        f"→ {webhook_url} (HTTP {response.status_code})"
                    )
                except httpx.HTTPStatusError as exc:
                    logger.error(
                        f"[Webhook] Server rejected payload for session {session_id}: "
                        f"HTTP {exc.response.status_code} — {exc.response.text[:200]}"
                    )
                except httpx.RequestError as exc:
                    logger.error(
                        f"[Webhook] Failed to reach webhook for session {session_id}: {exc}"
                    )
            else:
                logger.warning(
                    f"[Webhook] WEBHOOK_URL not configured — skipping push for session {session_id}. "
                    "Add 'WEBHOOK_URL' to api_keys.json to enable webhook delivery."
                )

        except Exception as exc:
            logger.error(f"[Evaluator] Background evaluation failed for {session_id}: {exc}")

    asyncio.create_task(_run())


# ========================================================================
# WebSocket Endpoint
# ========================================================================

@app.websocket("/ws/interview/{session_id}")
async def websocket_interview(websocket: WebSocket, session_id: str):
    """
    Real-time interview session over WebSocket.

    Protocol:
    1. Client connects -> server activates session, sends INTRO + TTS
    2. Client sends answers (text or audio) -> server processes, responds
    3. Loop until interview completes
    4. Server sends final report, closes connection
    """
    await websocket.accept()
    logger.info(f"[WS {session_id}] Client connected")
    orchestrator = None

    try:
        # -- Activate session and get orchestrator -------------------------
        try:
            orchestrator = session_manager.activate_session(session_id)
        except SessionNotFoundError:
            await _ws_send_error(websocket, f"Session not found: {session_id}")
            await websocket.close(code=4004, reason="Session not found")
            return
        except SessionStateError as e:
            await _ws_send_error(websocket, str(e))
            await websocket.close(code=4009, reason="Invalid session state")
            return

        # Build technical prompt for STT accuracy
        plan = orchestrator._plan
        skills = [q.skill for q in plan.questions]
        stt_prompt = build_technical_prompt(skills, plan.job_role)

        # -- INTRO phase ---------------------------------------------------
        logger.info(f"[WS {session_id}] Starting INTRO")
        intro_response = await orchestrator.start()

        await _ws_send_interviewer_message(
            websocket,
            msg_type="intro",
            response=intro_response,
        )

        # Stream TTS for intro
        await _ws_stream_tts(websocket, intro_response.text)

        # -- Session-level timer -------------------------------------------
        duration_limit = getattr(plan, "duration_limit", 1800)
        session_deadline = time.monotonic() + duration_limit

        # -- Main interview loop -------------------------------------------
        while not orchestrator.is_complete:
            # ── Session timeout check ────────────────────────────────────
            remaining = session_deadline - time.monotonic()
            if remaining <= 0:
                logger.info(f"[WS {session_id}] Session time limit reached")
                response = await orchestrator.force_timeout()
                await _ws_send_interviewer_message(websocket, msg_type="close", response=response)
                await _ws_stream_tts(websocket, response.text)
                report = orchestrator.get_report()
                await _save_and_evaluate(session_id, report)
                await websocket.send_json({"type": "complete"})
                break

            # ── Wait for candidate's answer ───────────────────────────────
            try:
                candidate_text = await asyncio.wait_for(
                    _ws_receive_answer(websocket, session_id, stt_prompt),
                    timeout=remaining,
                )
            except asyncio.TimeoutError:
                # Session time limit expired while waiting for candidate
                logger.info(f"[WS {session_id}] Session time limit reached while waiting")
                response = await orchestrator.force_timeout()
                await _ws_send_interviewer_message(websocket, msg_type="close", response=response)
                await _ws_stream_tts(websocket, response.text)
                report = orchestrator.get_report()
                await _save_and_evaluate(session_id, report)
                await websocket.send_json({"type": "complete"})
                logger.info(f"[WS {session_id}] Interview completed (session timeout)")
                break

            # ── End session signal ────────────────────────────────────────
            if candidate_text == "!END_SESSION!":
                logger.info(f"[WS {session_id}] User explicitly ended session.")
                await orchestrator.force_early_close()
                report = orchestrator.get_report()
                await _save_and_evaluate(session_id, report)
                try:
                    await websocket.send_json({"type": "complete"})
                except Exception:
                    pass
                break

            if candidate_text is None:
                break

            logger.info(f"[WS {session_id}] Candidate said: {candidate_text}")

            # ── Clarification check ───────────────────────────────────────
            intent = await orchestrator.get_candidate_intent(candidate_text)
            if intent == "clarification":
                response = await orchestrator.handle_clarification(candidate_text)
                logger.info(f"[WS {session_id}] Clarification detected")
                await _ws_send_interviewer_message(
                    websocket, msg_type="clarification", response=response,
                )
                await _ws_stream_tts(websocket, response.text)
                continue  # wait for the real answer; do NOT advance state
            elif intent == "answer_seeking":
                response = await orchestrator.handle_answer_seeking(candidate_text)
                logger.info(f"[WS {session_id}] Answer seeking detected")
                await _ws_send_interviewer_message(
                    websocket, msg_type="clarification", response=response,
                )
                await _ws_stream_tts(websocket, response.text)
                continue  # wait for the real answer; do NOT advance state
            elif intent == "off_topic":
                response = await orchestrator.handle_off_topic(candidate_text)
                logger.info(f"[WS {session_id}] Off-topic detected")
                await _ws_send_interviewer_message(
                    websocket, msg_type="clarification", response=response,
                )
                await _ws_stream_tts(websocket, response.text)
                continue  # redirect and wait for the real answer; do NOT advance state

            # ── Normal answer processing ──────────────────────────────────
            response = await orchestrator.handle_answer(candidate_text)

            if response.is_complete:
                msg_type = "close"
            elif response.state == "FOLLOWUP":
                msg_type = "followup"
            else:
                msg_type = "question"

            await _ws_send_interviewer_message(
                websocket, msg_type=msg_type, response=response,
            )
            await _ws_stream_tts(websocket, response.text)

            if response.is_complete:
                report = orchestrator.get_report()
                await _save_and_evaluate(session_id, report)
                await websocket.send_json({"type": "complete"})
                logger.info(f"[WS {session_id}] Interview completed")
                break

    except WebSocketDisconnect:
        logger.info(f"[WS {session_id}] Client disconnected")
        if orchestrator and not orchestrator.is_complete:
            logger.info(f"[WS {session_id}] Saving partial data after disconnect.")
            try:
                await orchestrator.force_early_close()
                report = orchestrator.get_report()
                report_storage.save_report(session_id, report)
            except Exception as e:
                logger.error(f"[WS {session_id}] Failed to save partial data: {e}")
    except Exception as exc:
        logger.error(f"[WS {session_id}] Error: {exc}", exc_info=True)
        try:
            await _ws_send_error(websocket, f"Internal error: {str(exc)}")
        except Exception:
            pass
    finally:
        logger.info(f"[WS {session_id}] Session ended")


# ========================================================================
# WebSocket helpers
# ========================================================================

async def _ws_send_interviewer_message(
    websocket: WebSocket,
    msg_type: str,
    response: Any,
) -> None:
    """Send the interviewer's text response as a JSON message."""
    message = {
        "type": msg_type,
        "text": response.text,
        "state": response.state,
        "question_index": response.question_index,
        "total_questions": response.total_questions,
    }

    if response.evaluation:
        message["evaluation"] = response.evaluation

    if response.followup_triggered:
        message["followup_triggered"] = True

    await websocket.send_json(message)


async def _ws_stream_tts(websocket: WebSocket, text: str) -> None:
    """Stream TTS audio chunks to the client."""
    try:
        # Signal TTS start
        await websocket.send_json({"type": "tts_start"})

        chunk_count = 0
        total_bytes = 0
        start = time.perf_counter()

        async for chunk in synthesize_streaming(text):
            await websocket.send_bytes(chunk)
            chunk_count += 1
            total_bytes += len(chunk)

        elapsed = (time.perf_counter() - start) * 1000

        # Signal TTS end
        await websocket.send_json({"type": "tts_end"})

        logger.debug(
            f"TTS streamed: {chunk_count} chunks, "
            f"{total_bytes:,} bytes, {elapsed:.0f}ms"
        )

    except Exception as exc:
        logger.error(f"TTS streaming error: {exc}")
        await websocket.send_json({
            "type": "tts_end",
            "error": str(exc),
        })


async def _ws_receive_answer(
    websocket: WebSocket,
    session_id: str,
    stt_prompt: str,
) -> Optional[str]:
    """
    Wait for the candidate's answer from the WebSocket.

    Handles two input modes:
    1. Text answer: { type: "answer", text: "..." }
    2. Audio answer: { type: "answer_audio" } followed by binary audio frame

    Returns the transcribed/provided text, or None on error.
    """
    try:
        # Receive the first message (could be text JSON or binary audio)
        message = await websocket.receive()

        # -- Text frame (JSON) --------------------------------------------
        if "text" in message:
            data = json.loads(message["text"])
            msg_type = data.get("type", "")

            if msg_type == "answer":
                # Pre-transcribed text answer
                return data.get("text", "").strip()

            elif msg_type == "end_session":
                return "!END_SESSION!"

            elif msg_type == "answer_audio":
                # Signal that the next frame will be binary audio
                audio_msg = await websocket.receive()
                if "bytes" in audio_msg:
                    return await _transcribe_audio(
                        audio_msg["bytes"], session_id, stt_prompt
                    )
                else:
                    logger.warning(
                        f"[WS {session_id}] Expected binary audio after answer_audio signal"
                    )
                    return None

            else:
                logger.warning(
                    f"[WS {session_id}] Unknown message type: {msg_type}"
                )
                return data.get("text", "").strip() or None

        # -- Binary frame (raw audio) -------------------------------------
        elif "bytes" in message:
            return await _transcribe_audio(
                message["bytes"], session_id, stt_prompt
            )

        return None

    except WebSocketDisconnect:
        raise
    except Exception as exc:
        logger.error(f"[WS {session_id}] Error receiving answer: {exc}")
        return None


async def _transcribe_audio(
    audio_bytes: bytes,
    session_id: str,
    stt_prompt: str,
) -> Optional[str]:
    """Transcribe audio bytes using STT (Groq Whisper)."""
    try:
        logger.info(
            f"[WS {session_id}] Transcribing {len(audio_bytes):,} bytes..."
        )

        # Run STT in a thread pool (it's a sync HTTP call)
        loop = asyncio.get_event_loop()
        result = await loop.run_in_executor(
            None,
            lambda: transcribe(
                audio_bytes=audio_bytes,
                filename="answer.webm",  # Most browsers record in WebM
                prompt=stt_prompt,
            ),
        )

        if result.is_empty:
            logger.warning(f"[WS {session_id}] STT returned empty transcription")
            return "I'm not sure, could you repeat the question?"

        logger.info(
            f"[WS {session_id}] STT: '{result.text[:60]}...' "
            f"({result.duration_ms:.0f}ms)"
        )

        return result.text

    except Exception as exc:
        logger.error(f"[WS {session_id}] STT failed: {exc}")
        return None


async def _ws_send_error(websocket: WebSocket, message: str) -> None:
    """Send an error message to the client."""
    await websocket.send_json({
        "type": "error",
        "message": message,
    })


# ========================================================================
# Run server
# ========================================================================

if __name__ == "__main__":
    import uvicorn

    port = get_key_int("API_PORT", "8000")
    host = get_key("API_HOST", "0.0.0.0")

    logger.info(f"Starting server on {host}:{port}")

    uvicorn.run(
        "api:app",
        host=host,
        port=port,
        reload=True,
        log_level="info",
    )
